// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"go-gf-blog/app/model/internal"
)

// ArticleTag is the golang structure for table t_article_tag.
type ArticleTag internal.ArticleTag

type QueryArticleTags struct {
	ArticleTag []*ArticleTag
}
