// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
	"go-gf-blog/app/model/internal"
)

// Article is the golang structure for table t_article.
type Article internal.Article

// 文章列表请求参数实体
type ApiArticlesListReq struct {
	CategoryId int    `p:"category_id"`
	PageNum    int    `p:"page"`
	PageSize   int    `p:"page_size"`
	Keywords   string `p:"keywords"`
	Status     int    `p:"status"`
	TagId      int    `p:"tag_id"`
}

// 用于查询文章列表时返回的文章实体
type QueryArticle struct {
	Id           uint        `orm:"id,primary"         json:"id"            c:"-"`             // 文章ID
	Title        string      `orm:"title"              json:"title"         c:"title"`         // 文章标题
	Summary      string      `orm:"summary"            json:"summary"       c:"summary"`       // 文章简介
	CategoryId   int         `orm:"category_id,unique" json:"category_id"   c:"category_id"`   // 文章栏目ID
	CategoryName string      `orm:"category_name"      json:"category_name" c:"category_name"` // 文章栏目名称
	Cover        string      `orm:"cover"              json:"cover"         c:"cover"`         // 文章封面
	UserId       int         `orm:"user_id"            json:"user_id"       c:"user_id"`       // 用户ID
	Author       string      `orm:"author"             json:"author"        c:"author"`        // 文章作者
	ClickCount   int         `orm:"click_count"        json:"click_count"   c:"click_count"`   // 文章点击数
	IsTop        int         `orm:"is_top"             json:"is_top"        c:"is_top"`        // 文章置顶:0-不置顶/1-置顶
	From         int         `orm:"from"               json:"from"          c:"from"`          // 文章来源:0-原创/1-转载/2-其他
	Status       int         `orm:"status"             json:"status"        c:"status"`        // 文章状态:1-发布/2-草稿/3-隐藏
	CreatedAt    *gtime.Time `orm:"created_at"         json:"created_at"    c:"created_at"`    // 创建时间
	UpdatedAt    *gtime.Time `orm:"updated_at"         json:"updated_at"    c:"updated_at"`    // 更新时间
}

// 用于查询文章列表时返回的文章标签实体
type QueryArticleTag struct {
	ArticleId int    `orm:"article_id" json:"article_id" c:"article_id"` // 文章ID
	TagId     int    `orm:"tag_id"     json:"tag_id"     c:"tag_id"`     // 标签ID
	TagName   string `orm:"tag_name"   json:"tag_name"   c:"tag_name"`   // 标签名称
}

type ArticleRes struct {
	Article *QueryArticle
	Tags    []*QueryArticleTag
}

// 添加文章请求实体
type ApiAddArticleReq struct {
	Title      string `p:"title"       v:"required#请填写文章标题"`
	Summary    string `p:"summary"`
	Cover      string `p:"cover"       v:"required#请上传文章封面"`
	CategoryId int    `p:"category_id" v:"required|min:1#请选择栏目|请选择栏目"`
	Tags       string `p:"tags"        v:"required#请选择标签"`
	From       int    `p:"from"        v:"required#请选择文章来源"`
	Status     int    `p:"status"      v:"required#请设置文章状态"`
	Content    string `p:"content"     v:"required#请填写文章内容"`
	MdContent  string `p:"md_content"  v:"required#Markdown内容错误"`
	Author     string `p:"author"`
	IsTop      int    `p:"is_top"`
}
