// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"go-gf-blog/app/model/internal"
)

// Link is the golang structure for table link.
type Link internal.Link

// 列表请求实体
type ApiLinkListReq struct {
	Sort int `p:"sort"`
	PageNum int `p:"page"`
	PageSize int `p:"page_size"`
}

// 添加链接请求实体
type ApiAddLinkReq struct {
	LinkName  string      `p:"link_name" v:"required#请填写链接名称"`
	LinkUrl   string      `p:"link_url"  v:"required#请填写链接地址"`
	IconUrl   string      `p:"icon_url"`
	Sort      int         `p:"sort"`
}
