// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"go-gf-blog/app/model/internal"
)

// Tag is the golang structure for table t_tag.
type Tag internal.Tag

// 新增标签请求实体
type ApiAddTagReq struct {
	Name string `p:"name" v:"required#请填写标签名称"`
}


// 删除标签请求实体
type ApiDeleteTagsReq struct {
	Ids interface{} `p:"ids" v:"required#请至少选择一个标签"`
}
