// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"go-gf-blog/app/model/internal"
)

// Tag is the golang structure for table t_tag.
type Tag internal.Tag

// Fill with you ideas below.