// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ArticleTag is the golang structure for table t_article_tag.
type ArticleTag struct {
    Id        int         `orm:"id,primary" json:"id"          c:"-"`          // 文章—标签-ID
    TagId     int         `orm:"tag_id"     json:"tag_id"      c:"tag_id"`     // 标签ID
    ArticleId int         `orm:"article_id" json:"article_id"  c:"article_id"` // 文章ID
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"  c:"created_id"` // 创建时间
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"  c:"updated_id"` // 更新时间
}
