// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Articles is the golang structure for table articles.
type Articles struct {
    Id         uint        `orm:"id,primary"  json:"id"           c:"-"`           // 文章ID
    Title      string      `orm:"title"       json:"title"        c:"title"`       // 文章标题
    Summary    string      `orm:"summary"     json:"summary"      c:"summary"`     // 文章简介绍
    CategoryId int         `orm:"category_id" json:"category_id"  c:"category_id"` // 文章栏目ID
    Tags       string      `orm:"tags"        json:"tags"         c:"tags"`        // 文章标签集合
    Cover      string      `orm:"cover"       json:"cover"        c:"cover"`       // 文章封面
    Content    string      `orm:"content"     json:"content"      c:"content"`     // 文章内容
    MdContent  string      `orm:"md_content"  json:"md_content"   c:"md_content"`  // 文章markdown内容
    Author     string      `orm:"author"      json:"author"       c:"author"`      // 作者
    ClickCount int         `orm:"click_count" json:"click_count"  c:"click_count"` // 文章点击数
    IsTop      int         `orm:"is_top"      json:"is_top"       c:"is_top"`      // 文章置顶:0-不置顶/1-置顶
    From       int         `orm:"from"        json:"from"         c:"from"`        // 文章来源:0-原创/1-转载/2-其他
    Status     int         `orm:"status"      json:"status"       c:"status"`      // 文章状态:1-发布/2-草稿/3-隐藏
    CreatedAt  *gtime.Time `orm:"created_at"  json:"created_at"   c:"created_at"`  // 创建时间
    UpdatedAt  *gtime.Time `orm:"updated_at"  json:"updated_at"   c:"updated_at"`  // 更新时间
}
