// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Categories is the golang structure for table categories.
type Categories struct {
    Id        uint        `orm:"id,primary" json:"id"         c:"-"`         //
    Name      string      `orm:"name"       json:"name"       c:"name"`       // 栏目名称
    Sort      int         `orm:"sort"       json:"sort"       c:"sort"`       // 栏目排序
    Status    int         `orm:"status"     json:"status"     c:"status"`     // 栏目状态:0-正常/1-隐藏
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at" c:"created_at"` //
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at" c:"updated_at"` //
}
