// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Config is the golang structure for table t_config.
type Config struct {
    Id          int         `orm:"id,primary"   json:"id"            c:"-"`            // 配置ID
    UpyBucket   string      `orm:"upy_bucket"   json:"upy_bucket"    c:"upy_bucket"`   // 又拍云存储服务名
    UpyOperator string      `orm:"upy_operator" json:"upy_operator"  c:"upy_operator"` // 又拍云操作员
    UpyPassword string      `orm:"upy_password" json:"upy_password"  c:"upy_password"` // 又拍云密码
    UpyUrl      string      `orm:"upy_url"      json:"upy_url"       c:"upy_url"`      // 又拍云存储域名
    CreatedAt   *gtime.Time `orm:"created_at"   json:"created_at"    c:"created_at"`   // 创建时间
    UpdatedAt   *gtime.Time `orm:"updated_at"   json:"updated_at"    c:"updated_at"`   // 更新时间
}
