// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Link is the golang structure for table link.
type Link struct {
    Id        int         `orm:"id,primary" json:"id"         c:"-"`         //
    LinkName  string      `orm:"link_name"  json:"link_name"  c:"link_name"`  //
    LinkUrl   string      `orm:"link_url"   json:"link_url"   c:"link_url"`   //
    IconUrl   string      `orm:"icon_url"   json:"icon_url"   c:"icon_url"`   //
    Sort      int         `orm:"sort"       json:"sort"       c:"sort"`       //
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at" c:"created_at"` //
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at" c:"updated_at"` //
}
