// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
    Id            uint        `orm:"id,primary"      json:"id"              c:"-"`                // 用户ID
    Passport      string      `orm:"passport"        json:"passport"        c:"passport"`         // 用户账号
    Password      string      `orm:"password"        json:"password"        c:"password"`         // 用户密码
    Nickname      string      `orm:"nickname"        json:"nickname"        c:"nickname"`         // 用户昵称
    Email         string      `orm:"email"           json:"email"           c:"email"`            // 邮箱
    Summary       string      `orm:"summary"         json:"summary"         c:"summary"`          // 自我简介
    Avatar        string      `orm:"avatar"          json:"avatar"          c:"avatar"`           // 头像地址
    WeChat        string      `orm:"we_chat"         json:"we_chat"         c:"we_chat"`          // 微信号
    LastLoginTime *gtime.Time `orm:"last_login_time" json:"last_login_time" c:"last_login_time"`  // 最后登录时间
    LastLoginIp   string      `orm:"last_login_ip"   json:"last_login_ip"   c:"last_login_ip"`    // 最后登录IP
    CreatedAt     *gtime.Time `orm:"created_at"      json:"created_at"      c:"created_at"`       // 创建时间
    UpdatedAt     *gtime.Time `orm:"updated_at"      json:"updated_at"      c:"updated_at"`       // 更新时间
}
