// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table t_user.
type User struct {
    Id            uint        `orm:"id,primary"      json:"id"`              // 用户ID        
    Passport      string      `orm:"passport"        json:"passport"`        // 用户账号      
    Password      string      `orm:"password"        json:"password"`        // 用户密码      
    Nickname      string      `orm:"nickname"        json:"nickname"`        // 用户昵称      
    Email         string      `orm:"email"           json:"email"`           // 邮箱          
    Summary       string      `orm:"summary"         json:"summary"`         // 自我简介      
    Avatar        string      `orm:"avatar"          json:"avatar"`          // 头像地址      
    GitHub        string      `orm:"git_hub"         json:"git_hub"`         // github帐号    
    WeChat        string      `orm:"we_chat"         json:"we_chat"`         // 微信号        
    LastLoginTime *gtime.Time `orm:"last_login_time" json:"last_login_time"` // 最后登录时间  
    LastLoginIp   string      `orm:"last_login_ip"   json:"last_login_ip"`   // 最后登录IP    
    CreatedAt     *gtime.Time `orm:"created_at"      json:"created_at"`      // 创建时间      
    UpdatedAt     *gtime.Time `orm:"updated_at"      json:"updated_at"`      // 更新时间      
}