# HTTP Server.
[server]
Address        = ":8199"
ServerAgent    = "go-gf-blog"
LogPath        = "/tmp/log/go-gf-blog/server"
NameToUriType  = 2
RouteOverWrite = true

# Logger configurations.
[logger]
Path   = "/tmp/log/go-gf-blog"
Level  = "all"
Stdout = true

# Database configurations.
[database]
link  = "mysql:root:xxx@tcp(xxx:3306)/go_gf_blog"
debug = true
# 数据库日志对象配置
[database.logger]
Path   = "/tmp/log/go-gf-blog/sql"
Level  = "all"
Stdout = true

# GF-CLI工具配置
[gfcli]
# 自定义DAO生成配置(默认是读取database配置)
[[gfcli.gen.dao]]
link   = "mysql:root:xxx@tcp(xxx:3306)/go_gf_blog"
tables = "t_user"
remove-prefix = "t_"

# HTTP basic authentication passport/password for swagger api page.
#[swagger]
#    user = "123"
#    pass = "123"

# 文件云储存相关设置
[file]
upy_key = "xxx"
