// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"go-gf-blog/app/dao/internal"
)

// categoryDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type categoryDao struct {
	*internal.CategoryDao
}

var (
	// Category is globally public accessible object for table t_category operations.
	Category = &categoryDao{
		internal.Category,
	}
)

// Fill with you ideas below.