// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"go-gf-blog/app/dao/internal"
)

// linkDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type linkDao struct {
	*internal.LinkDao
}

var (
	// Link is globally public accessible object for table link operations.
	Link = &linkDao{
		internal.Link,
	}
)

// Fill with you ideas below.