// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package categories

// 列表查询请求实体
type ApiQueryReq struct {
	Id int `p:"id"`
	Status int `p:"status"`
}

// 增加分类请求实体
type ApiAddReq struct {
	Name   string `p:"name" v:"required#请输入正确的分类名称"`
	Sort   int    `p:"sort" v:"required|integer#请填写设置排序|排序必须是整数"`
	Status int    `p:"status" v:"required|in:0,1#请选择状态|状态必须在0和1之间"`
}
