// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"context"
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"time"

	"go-gf-blog/app/model"
)

// ArticleDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ArticleDao struct {
	gmvc.M
	Table   string
	Columns articleColumns
}

// ArticleColumns defines and stores column names for table t_article.
type articleColumns struct {
	Id          string //                                
    Title       string // 文章标题                       
    Summary     string // 文章简介                       
    CategoryId  string // 文章栏目ID                     
    Cover       string // 文章封面                       
    Content     string // 文章内容                       
    MdContent   string // 文章markdown内容               
    UserId      string // 用户ID                         
    Author      string // 文章作者                       
    ClickCount  string // 文章点击数                     
    IsTop       string // 文章置顶:0-不置顶/1-置顶       
    From        string // 文章来源:0-原创/1-转载/2-其他  
    Status      string // 文章状态:1-发布/2-草稿/3-隐藏  
    CreatedAt   string // 创建时间                       
    UpdatedAt   string // 更新时间
}

var (
	// Article is globally public accessible object for table t_article operations.
	Article = &ArticleDao{
		M:     g.DB("default").Model("t_article").Safe(),
		Table: "t_article",
		Columns: articleColumns{
			Id:         "id",           
            Title:      "title",        
            Summary:    "summary",      
            CategoryId: "category_id",  
            Cover:      "cover",        
            Content:    "content",      
            MdContent:  "md_content",   
            UserId:     "user_id",      
            Author:     "author",       
            ClickCount: "click_count",  
            IsTop:      "is_top",       
            From:       "from",         
            Status:     "status",       
            CreatedAt:  "created_at",   
            UpdatedAt:  "updated_at",
		},
	}
)

// Ctx is a chaining function, which creates and returns a new DB that is a shallow copy
// of current DB object and with given context in it.
// Note that this returned DB object can be used only once, so do not assign it to
// a global or package variable for long using.
func (d *ArticleDao) Ctx(ctx context.Context) *ArticleDao {
	return &ArticleDao{M:d.M.Ctx(ctx)}
}

// As sets an alias name for current table.
func (d *ArticleDao) As(as string) *ArticleDao {
	return &ArticleDao{M:d.M.As(as)}
}

// TX sets the transaction for current operation.
func (d *ArticleDao) TX(tx *gdb.TX) *ArticleDao {
	return &ArticleDao{M:d.M.TX(tx)}
}

// Master marks the following operation on master node.
func (d *ArticleDao) Master() *ArticleDao {
	return &ArticleDao{M:d.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (d *ArticleDao) Slave() *ArticleDao {
	return &ArticleDao{M:d.M.Slave()}
}

// Args sets custom arguments for model operation.
func (d *ArticleDao) Args(args ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.Args(args ...)}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *ArticleDao) LeftJoin(table ...string) *ArticleDao {
	return &ArticleDao{M:d.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *ArticleDao) RightJoin(table ...string) *ArticleDao {
	return &ArticleDao{M:d.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *ArticleDao) InnerJoin(table ...string) *ArticleDao {
	return &ArticleDao{M:d.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *ArticleDao) Fields(fieldNamesOrMapStruct ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.Fields(fieldNamesOrMapStruct...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *ArticleDao) FieldsEx(fieldNamesOrMapStruct ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.FieldsEx(fieldNamesOrMapStruct...)}
}

// Option sets the extra operation option for the model.
func (d *ArticleDao) Option(option int) *ArticleDao {
	return &ArticleDao{M:d.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (d *ArticleDao) OmitEmpty() *ArticleDao {
	return &ArticleDao{M:d.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (d *ArticleDao) Filter() *ArticleDao {
	return &ArticleDao{M:d.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (d *ArticleDao) Where(where interface{}, args ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (d *ArticleDao) WherePri(where interface{}, args ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (d *ArticleDao) And(where interface{}, args ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (d *ArticleDao) Or(where interface{}, args ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (d *ArticleDao) Group(groupBy string) *ArticleDao {
	return &ArticleDao{M:d.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (d *ArticleDao) Order(orderBy ...string) *ArticleDao {
	return &ArticleDao{M:d.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (d *ArticleDao) Limit(limit ...int) *ArticleDao {
	return &ArticleDao{M:d.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (d *ArticleDao) Offset(offset int) *ArticleDao {
	return &ArticleDao{M:d.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (d *ArticleDao) Page(page, limit int) *ArticleDao {
	return &ArticleDao{M:d.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (d *ArticleDao) Batch(batch int) *ArticleDao {
	return &ArticleDao{M:d.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (d *ArticleDao) Cache(duration time.Duration, name ...string) *ArticleDao {
	return &ArticleDao{M:d.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (d *ArticleDao) Data(data ...interface{}) *ArticleDao {
	return &ArticleDao{M:d.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*model.Article.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *ArticleDao) All(where ...interface{}) ([]*model.Article, error) {
	all, err := d.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Article
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *model.Article.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *ArticleDao) One(where ...interface{}) (*model.Article, error) {
	one, err := d.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Article
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (d *ArticleDao) FindOne(where ...interface{}) (*model.Article, error) {
	one, err := d.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.Article
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *ArticleDao) FindAll(where ...interface{}) ([]*model.Article, error) {
	all, err := d.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.Article
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Struct retrieves one record from table and converts it into given struct.
// The parameter <pointer> should be type of *struct/**struct. If type **struct is given,
// it can create the struct internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not nil.
//
// Eg:
// user := new(User)
// err  := dao.User.Where("id", 1).Struct(user)
//
// user := (*User)(nil)
// err  := dao.User.Where("id", 1).Struct(&user)
func (d *ArticleDao) Struct(pointer interface{}, where ...interface{}) error {
	return d.M.Struct(pointer, where...)
}

// Structs retrieves records from table and converts them into given struct slice.
// The parameter <pointer> should be type of *[]struct/*[]*struct. It can create and fill the struct
// slice internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not empty.
//
// Eg:
// users := ([]User)(nil)
// err   := dao.User.Structs(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Structs(&users)
func (d *ArticleDao) Structs(pointer interface{}, where ...interface{}) error {
	return d.M.Structs(pointer, where...)
}

// Scan automatically calls Struct or Structs function according to the type of parameter <pointer>.
// It calls function Struct if <pointer> is type of *struct/**struct.
// It calls function Structs if <pointer> is type of *[]struct/*[]*struct.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved and given pointer is not empty or nil.
//
// Eg:
// user  := new(User)
// err   := dao.User.Where("id", 1).Scan(user)
//
// user  := (*User)(nil)
// err   := dao.User.Where("id", 1).Scan(&user)
//
// users := ([]User)(nil)
// err   := dao.User.Scan(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Scan(&users)
func (d *ArticleDao) Scan(pointer interface{}, where ...interface{}) error {
	return d.M.Scan(pointer, where...)
}

// Chunk iterates the table with given size and callback function.
func (d *ArticleDao) Chunk(limit int, callback func(entities []*model.Article, err error) bool) {
	d.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*model.Article
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (d *ArticleDao) LockUpdate() *ArticleDao {
	return &ArticleDao{M:d.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (d *ArticleDao) LockShared() *ArticleDao {
	return &ArticleDao{M:d.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (d *ArticleDao) Unscoped() *ArticleDao {
	return &ArticleDao{M:d.M.Unscoped()}
}